# Site settings
title: hallebear
email: halle@mestery.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog where I share my thoughts on everything!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hallebear.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  hallebear

# Build settings
markdown: kramdown
